version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USER}/kittygram_backend:latest
    container_name: backend
    env_file:
      - .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - postgres
    expose:
      - "8000"

  frontend:
    image: ${DOCKERHUB_USER}/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - static:/app/build

  gateway:
    image: ${DOCKERHUB_USER}/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend