server {
    listen 80;
    server_name _;

    index index.html;

    location /api/ {
        proxy_pass http://backend:9000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://backend:9000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # location /static/ {
    #     alias /static/;
    # }

    location /static/js/ {
        alias /static/static/js/;
    }

    location /static/css/ {
        alias /static/static/css/;
    }

    location /static/media/ {
        alias /static/static/media/;
    }

    # location /static/admin/ {
    #     alias /static/admin/;
    # }

    location /static/admin/css {
        alias /static/admin/css/;
    }

    location /static/admin/js {
        alias /static/admin/js/;
    }

    location /static/admin/fonts {
        alias /static/admin/fonts/;
    }

    location /static/admin/img {
        alias /static/admin/img/;
    }

    location /static/rest_framework/ {
        alias /static/rest_framework/;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        alias /static/;
        try_files $uri $uri/ /index.html;
    }

}